### ISSUE TITLE
DMD incorrect HGNCId and InheritanceMode

### ISSUE THREAD

**Issue by ehre** [Clinical-Genomics/reference-files#62] opened 2023-06-29 11:54 UTC
The file variant_catalog_grch38.json contains errors for DMD:

"HGNCId": 2933. This refers to DMPK. Should be 2928 for DMD.

"InheritanceMode": "AD". Should be "XL" (or "XR") for DMD.

**Comment by dnil** [comment] 2023-06-29 12:43
Hi, thank you for reporting! This is a partial duplicate of https://github.com/Clinical-Genomics/reference-files/issues/60, which was fixed a while back. But I did miss the inheritance pattern, which was no doubt inherited from the same gene the faulty id came from. Will fix!

**Closed** 2023-06-29 14:56 UTC
